### ISSUE TITLE
Ability to skip projects

### ISSUE THREAD

**Issue by tishun** [frieder/virgo-maven-plugin#6]
Hey there, awesome plugin!

We have a hierarchical maven build, where the parent projects are of type "pom".
Since "pom' projects are not supported by the plugin, as per 

BaseMojo.java#L225
> 		} else {
>			throw new MojoFailureException("The given Maven packaging type is currently not supported");
>		}

we can't actually call the virgo:deploy on the parent (that would subsequently deploy all childs that could be deployed).

It would be nice to either have a "skip" configuration flag (that one could put on projects that are not deployable) or simply print out WARN message and skip by default any such project.

What do you think? 

(I can help with developing this if it makes sense to you)

**Comment by frieder** [comment]
Hi there

Sorry for the late response and I'm glad you like this plugin. Unfortunately I don't work with Virgo anymore and therefore haven't taken care of the plugin either. There are a couple of people though who have forked this project and added new features to it. Maybe you can contact them and see if anyone wants to take the lead for this plugin and merge all those features into one. Or maybe it can even be added to the official tooling (that's why I had put it under the Eclipse license in the first place). Maintenance should be minimal (especially since development of Virgo has slowed down significantly).

Then you can extend it from there with all the other features (par, plan, pom etc.) already included.  As for me I just left (and will leave) the plugin here for the public benefit but I won't work on it in the forseeable future (due to lack of spare time).

Cheers
Frieder

**Comment by tishun** [comment]
Sure, thanks for replying!
